# Generated by Django 3.2 on 2023-07-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grossarylist',
            name='ingridient_id',
        ),
        migrations.RemoveField(
            model_name='grossarylist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='grossarylist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='like_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='GrossaryList',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
