# Generated by Django 3.2 on 2023-08-02 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000, 'Количество < 1000'), django.core.validators.MinValueValidator(1, 'Количество > 0')], verbose_name='Количество ингредиента'),
        ),
    ]
