# Generated by Django 3.2 on 2023-08-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_name_measurement_unit_ingredient',
        ),
    ]
