# Generated by Django 3.2 on 2023-08-02 16:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, following=django.db.models.expressions.F('follower')), name='non selfsubcribtion'),
        ),
    ]
